version: '3.7'

services:
  yoi_how:
    tty: true
    container_name: joi_how
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - '.:/app'
      - '/app/node_modules'
    ports:
      - 3006:3006
    environment:
      - CHOKIDAR_USEPOLLING=true